title: "Elide"
tagline: "Model Driven Json API and GraphQL Web Services for Java"
description: "Model Driven Json API and GraphQL Web Services for Java"
baseurl: ""
url: "https://elide.io"
logo: "/assets/images/elide-logo.svg"
# jekyll configuration
exclude: ["README.md"]

# build settings
markdown: kramdown
sass:
  load_paths:
    - _sass
    - node_modules
exclude: []

plugins:
  - jekyll-seo-tag

# site-specific configuration
BASE_PATH: https://elide.io
ASSET_PATH: /assets
