title: "Elide"
tagline: "JSON API and GraphQL Web Services"
description: "A Java library to build model driven JSON API and GraphQL web services with minimal effort"
baseurl: ""
url: "https://elide.io"
logo: "/assets/images/elide-logo.svg"
# jekyll configuration
exclude: ["README.md"]

# build settings
markdown: kramdown
sass:
  load_paths:
    - _sass
    - node_modules
exclude: []

plugins:
  - jekyll-seo-tag

# site-specific configuration
BASE_PATH: https://elide.io
ASSET_PATH: /assets
