files:
  - Spring
  - Elide Standalone

Spring: |+2
  <br/>
  Configure in `application.yaml`.

  ```yaml
  elide:
    aggregation-store:
      dynamic-config:
        path: src/resources/configs
  ```

Elide Standalone: |+2
  <br/>
  Override `ElideStandaloneSettings`.

  ```java
  public abstract class Settings implements ElideStandaloneSettings {
      @Override
      public ElideStandaloneAnalyticSettings getAnalyticProperties() {
          return new ElideStandaloneAnalyticSettings() {
              @Override
              public String getDynamicConfigPath() {
                  return File.separator + "configs" + File.separator;
              }
          };
      }
  }
  ```
