files:
  - Spring
  - Elide Standalone

Spring: |+2
  ```yaml
  # application.yaml

  elide:
    dynamic-config:
      path: src/resources/configs
  ```

Elide Standalone: |+2
  ```java
  //Override ElideStandaloneSettings

  @Override
  public ElideStandaloneAnalyticSettings getAnalyticProperties() {
      return new ElideStandaloneAnalyticSettings() {
          @Override
          public String getDynamicConfigPath() {
              return File.separator + "configs" + File.separator;
          }
      };
  }
  ```
