files:
  - Spring
  - Elide Standalone

Spring: |+2
  ```yaml
  elide:
    async:
      threadPoolSize: 10
      maxRunTimeMinutes: 120
      queryCleanupDays: 10
      queryCancellationIntervalSeconds: 600
      maxAsyncAfterSeconds: 30
      export:
        enabled: true
        path: /export
        skipCSVHeader: false
        storageDestination: /tmp
  ```

Elide Standalone: |+2
  ```java
  @Override
  public ElideStandaloneAsyncSettings getAsyncProperties() {
      ElideStandaloneAsyncSettings asyncProperties = new ElideStandaloneAsyncSettings() {
          @Override
          default Integer getThreadSize() {
              return 10;
          }

          @Override
          default Integer getMaxRunTimeSeconds() {
              return 120;
          }

          @Override
          default Integer getQueryCleanupDays() {
              return 10;
          }

          @Override
          default Integer getQueryCancelCheckIntervalSeconds() {
              return 600;
          }

          @Override
          default Integer getMaxAsyncAfterSeconds() {
              return 30;
          }

          @Override
          default String getExportApiPathSpec() {
              return "/export/*";
          }

          @Override
          default boolean enableExport() {
              return false;
          }

          @Override
          default boolean skipCSVHeader() {
              return false;
          }

          @Override
          default String getStorageDestination() {
              return "/tmp";
          }

          @Override
          default Integer getExportAsyncResponseTimeoutSeconds() {
              return 30;
          }

          @Override
          default ExecutorService getExportAsyncResponseExecutor() {
              return enableExport() ? Executors.newFixedThreadPool(getThreadSize() == null ? 6 : getThreadSize()) : null;
          }
      }
      return asyncProperties;
  }
  ```
