files:
  - Spring
  - Elide Standalone

Spring: |+2
  ```yaml
  # application.yaml

  elide:
    graphql:
      subscription:
        enabled: true
        path: /subscription
        idle-timeout: 30000ms
        max-message-size: 10000
        max-subscriptions: 30
        connection-timeout: 5000ms
  ```

Elide Standalone: |+2
  ```java
  //Override ElideStandaloneSettings

  @Override
  public ElideStandaloneSubscriptionSettings getSubscriptionProperties() {
      return new ElideStandaloneSubscriptionSettings() { 

          @Override
          public boolean enabled() {
              return true;
          }

          @Override
          public String getPath() {
              return "/subscription";
          }

          @Override
          public Duration getConnectionTimeout() {
              return Duration.ofMillis(5000L);
          }
          
          @Override
          public Integer getMaxSubscriptions() {
              return 30;
          }
          
          @Override
          public Integer getMaxMessageSize() {
              return 10000;
          }
          
          @Override
          public Duration getIdleTimeout() {
              return Duration.ofMillis(300000L);
          }
      };
  }
  ```
