files:
  - Spring
  - Elide Standalone

Spring: |+2
  ```yaml
  # application.yaml

  elide:
    subscription:
      enabled: true
      path: /subscription
      idleTimeoutMs: 30000
      maxMessageSize: 10000
      maxSubscriptions: 30
      connectionTimeoutMs: 5000
  ```

Elide Standalone: |+2
  ```java
  //Override ElideStandaloneSettings

  @Override
  public ElideStandaloneSubscriptionSettings getSubscriptionProperties() {
      return new ElideStandaloneSubscriptionSettings() { 

          @Override
          public boolean enabled() {
              return true;
          }

          @Override
          public String getPath() {
              return "/subscription";
          }

          @Override
          public Integer getConnectionTimeoutMs() {
              return 5000;
          }
          
          @Override
          public Integer getMaxSubscriptions() {
              return 30;
          }
          
          @Override
          public Integer getMaxMessageSize() {
              return 10000;
          }
          
          @Override
          public Long getIdleTimeoutMs() {
              return 300000L;
          }
      };
  }
  ```
